var wms_layers = [];


        var lyr_openstreetmap_0 = new ol.layer.Tile({
            'title': 'open street map',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_ParkingLotsByCBDistrictGraduated_1 = new ol.format.GeoJSON();
var features_ParkingLotsByCBDistrictGraduated_1 = format_ParkingLotsByCBDistrictGraduated_1.readFeatures(json_ParkingLotsByCBDistrictGraduated_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ParkingLotsByCBDistrictGraduated_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ParkingLotsByCBDistrictGraduated_1.addFeatures(features_ParkingLotsByCBDistrictGraduated_1);
var lyr_ParkingLotsByCBDistrictGraduated_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_ParkingLotsByCBDistrictGraduated_1, 
                style: style_ParkingLotsByCBDistrictGraduated_1,
                popuplayertitle: 'Parking Lots By CB District Graduated ',
                interactive: true,
    title: 'Parking Lots By CB District Graduated <br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_0.png" /> 0 - 0<br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_1.png" /> 0 - 25000<br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_2.png" /> 25000 - 50000<br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_3.png" /> 50000 - 100000<br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_4.png" /> 100000 - 200000<br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_5.png" /> 200000 - 400000<br />\
    <img src="styles/legend/ParkingLotsByCBDistrictGraduated_1_6.png" /> 400000 - 800000<br />' });
var format_Highviabilityredevelopmentparcel_2 = new ol.format.GeoJSON();
var features_Highviabilityredevelopmentparcel_2 = format_Highviabilityredevelopmentparcel_2.readFeatures(json_Highviabilityredevelopmentparcel_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Highviabilityredevelopmentparcel_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Highviabilityredevelopmentparcel_2.addFeatures(features_Highviabilityredevelopmentparcel_2);
var lyr_Highviabilityredevelopmentparcel_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Highviabilityredevelopmentparcel_2, 
                style: style_Highviabilityredevelopmentparcel_2,
                popuplayertitle: 'High viability redevelopment parcel',
                interactive: true,
                title: '<img src="styles/legend/Highviabilityredevelopmentparcel_2.png" /> High viability redevelopment parcel'
            });
var format_Cityownedsurfaceparkinglots_3 = new ol.format.GeoJSON();
var features_Cityownedsurfaceparkinglots_3 = format_Cityownedsurfaceparkinglots_3.readFeatures(json_Cityownedsurfaceparkinglots_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Cityownedsurfaceparkinglots_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Cityownedsurfaceparkinglots_3.addFeatures(features_Cityownedsurfaceparkinglots_3);
var lyr_Cityownedsurfaceparkinglots_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Cityownedsurfaceparkinglots_3, 
                style: style_Cityownedsurfaceparkinglots_3,
                popuplayertitle: 'City owned surface parking lots',
                interactive: true,
                title: '<img src="styles/legend/Cityownedsurfaceparkinglots_3.png" /> City owned surface parking lots'
            });
var format_MTASubwayLines_4 = new ol.format.GeoJSON();
var features_MTASubwayLines_4 = format_MTASubwayLines_4.readFeatures(json_MTASubwayLines_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MTASubwayLines_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MTASubwayLines_4.addFeatures(features_MTASubwayLines_4);
var lyr_MTASubwayLines_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MTASubwayLines_4, 
                style: style_MTASubwayLines_4,
                popuplayertitle: 'MTA Subway Lines',
                interactive: true,
                title: '<img src="styles/legend/MTASubwayLines_4.png" /> MTA Subway Lines'
            });
var format_MileFromRailTransit_5 = new ol.format.GeoJSON();
var features_MileFromRailTransit_5 = format_MileFromRailTransit_5.readFeatures(json_MileFromRailTransit_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MileFromRailTransit_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MileFromRailTransit_5.addFeatures(features_MileFromRailTransit_5);
var lyr_MileFromRailTransit_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MileFromRailTransit_5, 
                style: style_MileFromRailTransit_5,
                popuplayertitle: '½ Mile From Rail Transit',
                interactive: true,
                title: '<img src="styles/legend/MileFromRailTransit_5.png" /> ½ Mile From Rail Transit'
            });

lyr_openstreetmap_0.setVisible(true);lyr_ParkingLotsByCBDistrictGraduated_1.setVisible(true);lyr_Highviabilityredevelopmentparcel_2.setVisible(true);lyr_Cityownedsurfaceparkinglots_3.setVisible(true);lyr_MTASubwayLines_4.setVisible(true);lyr_MileFromRailTransit_5.setVisible(true);
var layersList = [lyr_openstreetmap_0,lyr_ParkingLotsByCBDistrictGraduated_1,lyr_Highviabilityredevelopmentparcel_2,lyr_Cityownedsurfaceparkinglots_3,lyr_MTASubwayLines_4,lyr_MileFromRailTransit_5];
lyr_ParkingLotsByCBDistrictGraduated_1.set('fieldAliases', {'fid': 'fid', 'boro_cd': 'boro_cd', 'shape_area': 'shape_area', 'shape_leng': 'shape_leng', 'Name': 'Name', 'count': 'count', 'sum': 'sum', });
lyr_Highviabilityredevelopmentparcel_2.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'Borough': 'Borough', 'Block': 'Block', 'Lot': 'Lot', 'CD': 'CD', 'BCT2020': 'BCT2020', 'BCTCB2020': 'BCTCB2020', 'CT2010': 'CT2010', 'CB2010': 'CB2010', 'SchoolDist': 'SchoolDist', 'Council': 'Council', 'ZipCode': 'ZipCode', 'FireComp': 'FireComp', 'PolicePrct': 'PolicePrct', 'HealthCenterDistrict': 'HealthCenterDistrict', 'HealthArea': 'HealthArea', 'Sanitboro': 'Sanitboro', 'SanitDistrict': 'SanitDistrict', 'SanitSub': 'SanitSub', 'Address': 'Address', 'ZoneDist1': 'ZoneDist1', 'ZoneDist2': 'ZoneDist2', 'ZoneDist3': 'ZoneDist3', 'ZoneDist4': 'ZoneDist4', 'Overlay1': 'Overlay1', 'Overlay2': 'Overlay2', 'SPDist1': 'SPDist1', 'SPDist2': 'SPDist2', 'SPDist3': 'SPDist3', 'LtdHeight': 'LtdHeight', 'SplitZone': 'SplitZone', 'BldgClass': 'BldgClass', 'LandUse': 'LandUse', 'Easements': 'Easements', 'OwnerType': 'OwnerType', 'OwnerName': 'OwnerName', 'LotArea': 'LotArea', 'BldgArea': 'BldgArea', 'ComArea': 'ComArea', 'ResArea': 'ResArea', 'OfficeArea': 'OfficeArea', 'RetailArea': 'RetailArea', 'GarageArea': 'GarageArea', 'StrgeArea': 'StrgeArea', 'FactryArea': 'FactryArea', 'OtherArea': 'OtherArea', 'AreaSource': 'AreaSource', 'NumBldgs': 'NumBldgs', 'NumFloors': 'NumFloors', 'UnitsRes': 'UnitsRes', 'UnitsTotal': 'UnitsTotal', 'LotFront': 'LotFront', 'LotDepth': 'LotDepth', 'BldgFront': 'BldgFront', 'BldgDepth': 'BldgDepth', 'Ext': 'Ext', 'ProxCode': 'ProxCode', 'IrrLotCode': 'IrrLotCode', 'LotType': 'LotType', 'BsmtCode': 'BsmtCode', 'AssessLand': 'AssessLand', 'AssessTot': 'AssessTot', 'ExemptTot': 'ExemptTot', 'YearBuilt': 'YearBuilt', 'YearAlter1': 'YearAlter1', 'YearAlter2': 'YearAlter2', 'HistDist': 'HistDist', 'Landmark': 'Landmark', 'BuiltFAR': 'BuiltFAR', 'ResidFAR': 'ResidFAR', 'CommFAR': 'CommFAR', 'FacilFAR': 'FacilFAR', 'BoroCode': 'BoroCode', 'BBL': 'BBL', 'CondoNo': 'CondoNo', 'Tract2010': 'Tract2010', 'XCoord': 'XCoord', 'YCoord': 'YCoord', 'ZoneMap': 'ZoneMap', 'ZMCode': 'ZMCode', 'Sanborn': 'Sanborn', 'TaxMap': 'TaxMap', 'EDesigNum': 'EDesigNum', 'APPBBL': 'APPBBL', 'APPDate': 'APPDate', 'PLUTOMapID': 'PLUTOMapID', 'FIRM07_FLAG': 'FIRM07_FLAG', 'PFIRM15_FLAG': 'PFIRM15_FLAG', 'Version': 'Version', 'DCPEdited': 'DCPEdited', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Notes': 'Notes', 'MIHOption1': 'MIHOption1', 'MIHOption2': 'MIHOption2', 'MIHOption3': 'MIHOption3', 'MIHOption4': 'MIHOption4', 'TrnstZone': 'TrnstZone', 'AffResFAR': 'AffResFAR', 'ManuFAR': 'ManuFAR', 'Shape_Leng': 'Shape_Leng', 'Shape_Length': 'Shape_Length', 'Shape_Area': 'Shape_Area', 'Res_Capacity': 'Res_Capacity', });
lyr_Cityownedsurfaceparkinglots_3.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'Borough': 'Borough', 'Block': 'Block', 'Lot': 'Lot', 'CD': 'CD', 'BCT2020': 'BCT2020', 'BCTCB2020': 'BCTCB2020', 'CT2010': 'CT2010', 'CB2010': 'CB2010', 'SchoolDist': 'SchoolDist', 'Council': 'Council', 'ZipCode': 'ZipCode', 'FireComp': 'FireComp', 'PolicePrct': 'PolicePrct', 'HealthCenterDistrict': 'HealthCenterDistrict', 'HealthArea': 'HealthArea', 'Sanitboro': 'Sanitboro', 'SanitDistrict': 'SanitDistrict', 'SanitSub': 'SanitSub', 'Address': 'Address', 'ZoneDist1': 'ZoneDist1', 'ZoneDist2': 'ZoneDist2', 'ZoneDist3': 'ZoneDist3', 'ZoneDist4': 'ZoneDist4', 'Overlay1': 'Overlay1', 'Overlay2': 'Overlay2', 'SPDist1': 'SPDist1', 'SPDist2': 'SPDist2', 'SPDist3': 'SPDist3', 'LtdHeight': 'LtdHeight', 'SplitZone': 'SplitZone', 'BldgClass': 'BldgClass', 'LandUse': 'LandUse', 'Easements': 'Easements', 'OwnerType': 'OwnerType', 'OwnerName': 'OwnerName', 'LotArea': 'LotArea', 'BldgArea': 'BldgArea', 'ComArea': 'ComArea', 'ResArea': 'ResArea', 'OfficeArea': 'OfficeArea', 'RetailArea': 'RetailArea', 'GarageArea': 'GarageArea', 'StrgeArea': 'StrgeArea', 'FactryArea': 'FactryArea', 'OtherArea': 'OtherArea', 'AreaSource': 'AreaSource', 'NumBldgs': 'NumBldgs', 'NumFloors': 'NumFloors', 'UnitsRes': 'UnitsRes', 'UnitsTotal': 'UnitsTotal', 'LotFront': 'LotFront', 'LotDepth': 'LotDepth', 'BldgFront': 'BldgFront', 'BldgDepth': 'BldgDepth', 'Ext': 'Ext', 'ProxCode': 'ProxCode', 'IrrLotCode': 'IrrLotCode', 'LotType': 'LotType', 'BsmtCode': 'BsmtCode', 'AssessLand': 'AssessLand', 'AssessTot': 'AssessTot', 'ExemptTot': 'ExemptTot', 'YearBuilt': 'YearBuilt', 'YearAlter1': 'YearAlter1', 'YearAlter2': 'YearAlter2', 'HistDist': 'HistDist', 'Landmark': 'Landmark', 'BuiltFAR': 'BuiltFAR', 'ResidFAR': 'ResidFAR', 'CommFAR': 'CommFAR', 'FacilFAR': 'FacilFAR', 'BoroCode': 'BoroCode', 'BBL': 'BBL', 'CondoNo': 'CondoNo', 'Tract2010': 'Tract2010', 'XCoord': 'XCoord', 'YCoord': 'YCoord', 'ZoneMap': 'ZoneMap', 'ZMCode': 'ZMCode', 'Sanborn': 'Sanborn', 'TaxMap': 'TaxMap', 'EDesigNum': 'EDesigNum', 'APPBBL': 'APPBBL', 'APPDate': 'APPDate', 'PLUTOMapID': 'PLUTOMapID', 'FIRM07_FLAG': 'FIRM07_FLAG', 'PFIRM15_FLAG': 'PFIRM15_FLAG', 'Version': 'Version', 'DCPEdited': 'DCPEdited', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Notes': 'Notes', 'MIHOption1': 'MIHOption1', 'MIHOption2': 'MIHOption2', 'MIHOption3': 'MIHOption3', 'MIHOption4': 'MIHOption4', 'TrnstZone': 'TrnstZone', 'AffResFAR': 'AffResFAR', 'ManuFAR': 'ManuFAR', 'Shape_Leng': 'Shape_Leng', 'Shape_Length': 'Shape_Length', 'Shape_Area': 'Shape_Area', 'Res_Capacity': 'Res_Capacity', });
lyr_MTASubwayLines_4.set('fieldAliases', {':id': ':id', ':version': ':version', ':created_at': ':created_at', ':updated_at': ':updated_at', 'objectid': 'objectid', 'service_name': 'service_name', 'service': 'service', 'shape_stlength': 'shape_stlength', });
lyr_MileFromRailTransit_5.set('fieldAliases', {'Complex ID': 'Complex ID', 'Is Complex': 'Is Complex', 'Number Of Stations In Complex': 'Number Of Stations In Complex', 'Stop Name': 'Stop Name', 'Display Name': 'Display Name', 'Constituent Station Names': 'Constituent Station Names', 'Station IDs': 'Station IDs', 'GTFS Stop IDs': 'GTFS Stop IDs', 'Borough': 'Borough', 'CBD': 'CBD', 'Daytime Routes': 'Daytime Routes', 'Structure Type': 'Structure Type', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'ADA': 'ADA', 'ADA Notes': 'ADA Notes', });
lyr_ParkingLotsByCBDistrictGraduated_1.set('fieldImages', {'fid': '', 'boro_cd': 'TextEdit', 'shape_area': 'TextEdit', 'shape_leng': 'TextEdit', 'Name': 'TextEdit', 'count': 'Range', 'sum': 'TextEdit', });
lyr_Highviabilityredevelopmentparcel_2.set('fieldImages', {'fid': '', 'OBJECTID': '', 'Borough': '', 'Block': '', 'Lot': '', 'CD': '', 'BCT2020': '', 'BCTCB2020': '', 'CT2010': '', 'CB2010': '', 'SchoolDist': '', 'Council': '', 'ZipCode': '', 'FireComp': '', 'PolicePrct': '', 'HealthCenterDistrict': '', 'HealthArea': '', 'Sanitboro': '', 'SanitDistrict': '', 'SanitSub': '', 'Address': '', 'ZoneDist1': '', 'ZoneDist2': '', 'ZoneDist3': '', 'ZoneDist4': '', 'Overlay1': '', 'Overlay2': '', 'SPDist1': '', 'SPDist2': '', 'SPDist3': '', 'LtdHeight': '', 'SplitZone': '', 'BldgClass': '', 'LandUse': '', 'Easements': '', 'OwnerType': '', 'OwnerName': '', 'LotArea': '', 'BldgArea': '', 'ComArea': '', 'ResArea': '', 'OfficeArea': '', 'RetailArea': '', 'GarageArea': '', 'StrgeArea': '', 'FactryArea': '', 'OtherArea': '', 'AreaSource': '', 'NumBldgs': '', 'NumFloors': '', 'UnitsRes': '', 'UnitsTotal': '', 'LotFront': '', 'LotDepth': '', 'BldgFront': '', 'BldgDepth': '', 'Ext': '', 'ProxCode': '', 'IrrLotCode': '', 'LotType': '', 'BsmtCode': '', 'AssessLand': '', 'AssessTot': '', 'ExemptTot': '', 'YearBuilt': '', 'YearAlter1': '', 'YearAlter2': '', 'HistDist': '', 'Landmark': '', 'BuiltFAR': '', 'ResidFAR': '', 'CommFAR': '', 'FacilFAR': '', 'BoroCode': '', 'BBL': '', 'CondoNo': '', 'Tract2010': '', 'XCoord': '', 'YCoord': '', 'ZoneMap': '', 'ZMCode': '', 'Sanborn': '', 'TaxMap': '', 'EDesigNum': '', 'APPBBL': '', 'APPDate': '', 'PLUTOMapID': '', 'FIRM07_FLAG': '', 'PFIRM15_FLAG': '', 'Version': '', 'DCPEdited': '', 'Latitude': '', 'Longitude': '', 'Notes': '', 'MIHOption1': '', 'MIHOption2': '', 'MIHOption3': '', 'MIHOption4': '', 'TrnstZone': '', 'AffResFAR': '', 'ManuFAR': '', 'Shape_Leng': '', 'Shape_Length': '', 'Shape_Area': '', 'Res_Capacity': '', });
lyr_Cityownedsurfaceparkinglots_3.set('fieldImages', {'OBJECTID': 'TextEdit', 'Borough': 'TextEdit', 'Block': 'Range', 'Lot': 'Range', 'CD': 'Range', 'BCT2020': 'TextEdit', 'BCTCB2020': 'TextEdit', 'CT2010': 'TextEdit', 'CB2010': 'TextEdit', 'SchoolDist': 'TextEdit', 'Council': 'Range', 'ZipCode': 'Range', 'FireComp': 'TextEdit', 'PolicePrct': 'Range', 'HealthCenterDistrict': 'Range', 'HealthArea': 'Range', 'Sanitboro': 'TextEdit', 'SanitDistrict': 'TextEdit', 'SanitSub': 'TextEdit', 'Address': 'TextEdit', 'ZoneDist1': 'TextEdit', 'ZoneDist2': 'TextEdit', 'ZoneDist3': 'TextEdit', 'ZoneDist4': 'TextEdit', 'Overlay1': 'TextEdit', 'Overlay2': 'TextEdit', 'SPDist1': 'TextEdit', 'SPDist2': 'TextEdit', 'SPDist3': 'TextEdit', 'LtdHeight': 'TextEdit', 'SplitZone': 'TextEdit', 'BldgClass': 'TextEdit', 'LandUse': 'TextEdit', 'Easements': 'Range', 'OwnerType': 'TextEdit', 'OwnerName': 'TextEdit', 'LotArea': 'Range', 'BldgArea': 'Range', 'ComArea': 'Range', 'ResArea': 'Range', 'OfficeArea': 'Range', 'RetailArea': 'Range', 'GarageArea': 'Range', 'StrgeArea': 'Range', 'FactryArea': 'Range', 'OtherArea': 'Range', 'AreaSource': 'TextEdit', 'NumBldgs': 'Range', 'NumFloors': 'TextEdit', 'UnitsRes': 'Range', 'UnitsTotal': 'Range', 'LotFront': 'TextEdit', 'LotDepth': 'TextEdit', 'BldgFront': 'TextEdit', 'BldgDepth': 'TextEdit', 'Ext': 'TextEdit', 'ProxCode': 'TextEdit', 'IrrLotCode': 'TextEdit', 'LotType': 'TextEdit', 'BsmtCode': 'TextEdit', 'AssessLand': 'TextEdit', 'AssessTot': 'TextEdit', 'ExemptTot': 'TextEdit', 'YearBuilt': 'Range', 'YearAlter1': 'Range', 'YearAlter2': 'Range', 'HistDist': 'TextEdit', 'Landmark': 'TextEdit', 'BuiltFAR': 'TextEdit', 'ResidFAR': 'TextEdit', 'CommFAR': 'TextEdit', 'FacilFAR': 'TextEdit', 'BoroCode': 'Range', 'BBL': 'TextEdit', 'CondoNo': 'Range', 'Tract2010': 'TextEdit', 'XCoord': 'Range', 'YCoord': 'Range', 'ZoneMap': 'TextEdit', 'ZMCode': 'TextEdit', 'Sanborn': 'TextEdit', 'TaxMap': 'TextEdit', 'EDesigNum': 'TextEdit', 'APPBBL': 'TextEdit', 'APPDate': 'TextEdit', 'PLUTOMapID': 'TextEdit', 'FIRM07_FLAG': 'TextEdit', 'PFIRM15_FLAG': 'TextEdit', 'Version': 'TextEdit', 'DCPEdited': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Notes': 'TextEdit', 'MIHOption1': 'TextEdit', 'MIHOption2': 'TextEdit', 'MIHOption3': 'TextEdit', 'MIHOption4': 'TextEdit', 'TrnstZone': 'TextEdit', 'AffResFAR': 'TextEdit', 'ManuFAR': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Length': 'TextEdit', 'Shape_Area': 'TextEdit', 'Res_Capacity': 'TextEdit', });
lyr_MTASubwayLines_4.set('fieldImages', {':id': 'TextEdit', ':version': 'TextEdit', ':created_at': 'DateTime', ':updated_at': 'DateTime', 'objectid': 'TextEdit', 'service_name': 'TextEdit', 'service': 'TextEdit', 'shape_stlength': 'TextEdit', });
lyr_MileFromRailTransit_5.set('fieldImages', {'Complex ID': 'Range', 'Is Complex': 'CheckBox', 'Number Of Stations In Complex': 'Range', 'Stop Name': 'TextEdit', 'Display Name': 'TextEdit', 'Constituent Station Names': 'TextEdit', 'Station IDs': 'TextEdit', 'GTFS Stop IDs': 'TextEdit', 'Borough': 'TextEdit', 'CBD': 'CheckBox', 'Daytime Routes': 'TextEdit', 'Structure Type': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'ADA': 'Range', 'ADA Notes': 'TextEdit', });
lyr_ParkingLotsByCBDistrictGraduated_1.set('fieldLabels', {'fid': 'no label', 'boro_cd': 'no label', 'shape_area': 'no label', 'shape_leng': 'no label', 'Name': 'no label', 'count': 'no label', 'sum': 'no label', });
lyr_Highviabilityredevelopmentparcel_2.set('fieldLabels', {'fid': 'no label', 'OBJECTID': 'no label', 'Borough': 'no label', 'Block': 'no label', 'Lot': 'no label', 'CD': 'no label', 'BCT2020': 'no label', 'BCTCB2020': 'no label', 'CT2010': 'no label', 'CB2010': 'no label', 'SchoolDist': 'no label', 'Council': 'no label', 'ZipCode': 'no label', 'FireComp': 'no label', 'PolicePrct': 'no label', 'HealthCenterDistrict': 'no label', 'HealthArea': 'no label', 'Sanitboro': 'no label', 'SanitDistrict': 'no label', 'SanitSub': 'no label', 'Address': 'no label', 'ZoneDist1': 'no label', 'ZoneDist2': 'no label', 'ZoneDist3': 'no label', 'ZoneDist4': 'no label', 'Overlay1': 'no label', 'Overlay2': 'no label', 'SPDist1': 'no label', 'SPDist2': 'no label', 'SPDist3': 'no label', 'LtdHeight': 'no label', 'SplitZone': 'no label', 'BldgClass': 'no label', 'LandUse': 'no label', 'Easements': 'no label', 'OwnerType': 'no label', 'OwnerName': 'no label', 'LotArea': 'no label', 'BldgArea': 'no label', 'ComArea': 'no label', 'ResArea': 'no label', 'OfficeArea': 'no label', 'RetailArea': 'no label', 'GarageArea': 'no label', 'StrgeArea': 'no label', 'FactryArea': 'no label', 'OtherArea': 'no label', 'AreaSource': 'no label', 'NumBldgs': 'no label', 'NumFloors': 'no label', 'UnitsRes': 'no label', 'UnitsTotal': 'no label', 'LotFront': 'no label', 'LotDepth': 'no label', 'BldgFront': 'no label', 'BldgDepth': 'no label', 'Ext': 'no label', 'ProxCode': 'no label', 'IrrLotCode': 'no label', 'LotType': 'no label', 'BsmtCode': 'no label', 'AssessLand': 'no label', 'AssessTot': 'no label', 'ExemptTot': 'no label', 'YearBuilt': 'no label', 'YearAlter1': 'no label', 'YearAlter2': 'no label', 'HistDist': 'no label', 'Landmark': 'no label', 'BuiltFAR': 'no label', 'ResidFAR': 'no label', 'CommFAR': 'no label', 'FacilFAR': 'no label', 'BoroCode': 'no label', 'BBL': 'no label', 'CondoNo': 'no label', 'Tract2010': 'no label', 'XCoord': 'no label', 'YCoord': 'no label', 'ZoneMap': 'no label', 'ZMCode': 'no label', 'Sanborn': 'no label', 'TaxMap': 'no label', 'EDesigNum': 'no label', 'APPBBL': 'no label', 'APPDate': 'no label', 'PLUTOMapID': 'no label', 'FIRM07_FLAG': 'no label', 'PFIRM15_FLAG': 'no label', 'Version': 'no label', 'DCPEdited': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'Notes': 'no label', 'MIHOption1': 'no label', 'MIHOption2': 'no label', 'MIHOption3': 'no label', 'MIHOption4': 'no label', 'TrnstZone': 'no label', 'AffResFAR': 'no label', 'ManuFAR': 'no label', 'Shape_Leng': 'no label', 'Shape_Length': 'no label', 'Shape_Area': 'no label', 'Res_Capacity': 'no label', });
lyr_Cityownedsurfaceparkinglots_3.set('fieldLabels', {'OBJECTID': 'no label', 'Borough': 'no label', 'Block': 'no label', 'Lot': 'no label', 'CD': 'no label', 'BCT2020': 'no label', 'BCTCB2020': 'no label', 'CT2010': 'no label', 'CB2010': 'no label', 'SchoolDist': 'no label', 'Council': 'no label', 'ZipCode': 'no label', 'FireComp': 'no label', 'PolicePrct': 'no label', 'HealthCenterDistrict': 'no label', 'HealthArea': 'no label', 'Sanitboro': 'no label', 'SanitDistrict': 'no label', 'SanitSub': 'no label', 'Address': 'no label', 'ZoneDist1': 'no label', 'ZoneDist2': 'no label', 'ZoneDist3': 'no label', 'ZoneDist4': 'no label', 'Overlay1': 'no label', 'Overlay2': 'no label', 'SPDist1': 'no label', 'SPDist2': 'no label', 'SPDist3': 'no label', 'LtdHeight': 'no label', 'SplitZone': 'no label', 'BldgClass': 'no label', 'LandUse': 'no label', 'Easements': 'no label', 'OwnerType': 'no label', 'OwnerName': 'no label', 'LotArea': 'no label', 'BldgArea': 'no label', 'ComArea': 'no label', 'ResArea': 'no label', 'OfficeArea': 'no label', 'RetailArea': 'no label', 'GarageArea': 'no label', 'StrgeArea': 'no label', 'FactryArea': 'no label', 'OtherArea': 'no label', 'AreaSource': 'no label', 'NumBldgs': 'no label', 'NumFloors': 'no label', 'UnitsRes': 'no label', 'UnitsTotal': 'no label', 'LotFront': 'no label', 'LotDepth': 'no label', 'BldgFront': 'no label', 'BldgDepth': 'no label', 'Ext': 'no label', 'ProxCode': 'no label', 'IrrLotCode': 'no label', 'LotType': 'no label', 'BsmtCode': 'no label', 'AssessLand': 'no label', 'AssessTot': 'no label', 'ExemptTot': 'no label', 'YearBuilt': 'no label', 'YearAlter1': 'no label', 'YearAlter2': 'no label', 'HistDist': 'no label', 'Landmark': 'no label', 'BuiltFAR': 'no label', 'ResidFAR': 'no label', 'CommFAR': 'no label', 'FacilFAR': 'no label', 'BoroCode': 'no label', 'BBL': 'no label', 'CondoNo': 'no label', 'Tract2010': 'no label', 'XCoord': 'no label', 'YCoord': 'no label', 'ZoneMap': 'no label', 'ZMCode': 'no label', 'Sanborn': 'no label', 'TaxMap': 'no label', 'EDesigNum': 'no label', 'APPBBL': 'no label', 'APPDate': 'no label', 'PLUTOMapID': 'no label', 'FIRM07_FLAG': 'no label', 'PFIRM15_FLAG': 'no label', 'Version': 'no label', 'DCPEdited': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'Notes': 'no label', 'MIHOption1': 'no label', 'MIHOption2': 'no label', 'MIHOption3': 'no label', 'MIHOption4': 'no label', 'TrnstZone': 'no label', 'AffResFAR': 'no label', 'ManuFAR': 'no label', 'Shape_Leng': 'no label', 'Shape_Length': 'no label', 'Shape_Area': 'no label', 'Res_Capacity': 'no label', });
lyr_MTASubwayLines_4.set('fieldLabels', {':id': 'no label', ':version': 'no label', ':created_at': 'header label - visible with data', ':updated_at': 'no label', 'objectid': 'no label', 'service_name': 'no label', 'service': 'no label', 'shape_stlength': 'no label', });
lyr_MileFromRailTransit_5.set('fieldLabels', {'Complex ID': 'no label', 'Is Complex': 'no label', 'Number Of Stations In Complex': 'no label', 'Stop Name': 'no label', 'Display Name': 'no label', 'Constituent Station Names': 'no label', 'Station IDs': 'no label', 'GTFS Stop IDs': 'no label', 'Borough': 'no label', 'CBD': 'no label', 'Daytime Routes': 'no label', 'Structure Type': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'ADA': 'no label', 'ADA Notes': 'no label', });
lyr_MileFromRailTransit_5.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});